---
title: "Get fq from CyVerse and Submit to SRA"
author: Jinliang Yang
date: 09-22-2017
output: html_notebook
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```

## Supplementary Figure

```{r, eval=FALSE}
######## methylation
stat <- read.delim("cache/maize_bismap_trimming_stat.txt", header=TRUE)
#stat$totpe <- gsub("\\s+|,|\\(.*|bp", "", stat$totpe)

res <- apply(stat[,-1], 2, function(x) gsub("\\s+|,|\\(.*|bp", "",x))
res <- as.data.frame(apply(res, 2, as.numeric))
res$files <- gsub("_.*", "", stat$files)

res$aptrimmed <- res$totbp - res$totout - res$qtrimmed

library(ggplot2)
library(tidyr)

lres <- gather(res[, 6:9], type, reads, c(1,2,4))
lres <- lres[order(lres$files, lres$type, decreasing = TRUE),]

lres$type <- factor(lres$type, levels = c("aptrimmed", "qtrimmed",  "totout"), 
                    labels=c("Adapter", "Q<20", "remaning"), ordered=TRUE)

theme_set(theme_grey(base_size = 18)) 
s <- ggplot(lres, aes(x=files, y=reads, fill = type)) + 
    #opts(axis.text.x=theme_text(angle=90)) +
    geom_bar(stat="identity") +
    labs(x="Accession ID", y="Base-pairs", fill="Trimming") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, size=12))

pdf("graphs/SFig_wgbs_trimming.pdf", width=10, height=5)
s
dev.off()
```

```{r}
pg20 <- read.csv("cache/pg20_bismap_stat.csv")

library(ggplot2)
library(tidyr)

mr <- gather(pg20[, c("seqid", "mr1","mr0", "mrN")], type, reads, 2:4)
mr$type <- factor(mr$type, levels = c("mr1", "mrN", "mr0"))
ratio <- gather(pg20[, c("seqid", "cg","chg", "chh")], type, cr, 2:4)
ratio$type <- factor(ratio$type, levels = c("cg", "chg", "chh"))

###### plot the mapping rate
p1 <- ggplot(mr, aes(x=type, y=reads, fill=type)) +
    geom_violin() +
    theme_bw() +
    theme(plot.title = element_text(color="red", size=20, face="bold.italic"),
          axis.text.x = element_text(size=18),
          axis.text.y = element_text(size=13),
          axis.title = element_text(size=18, face="bold")) +
    #scale_fill_manual(values=c("#008080", "#003366", "#40e0d0")) +
    scale_x_discrete(labels=c("Unqiue", "Multiple", "Non")) +
    ggtitle("Mapping Rate (N=20)") + xlab("") + 
    ylab("Mapping Rate") + 
    guides(fill=FALSE)
#guides(colour=FALSE, linetype=FALSE)
###### plot the mapping rate
p2 <- ggplot(ratio, aes(x=type, y=cr, fill=type)) +
    geom_boxplot() +
    theme_bw() +
    theme(plot.title = element_text(color="red", size=20, face="bold.italic"),
          axis.text.x = element_text(size=18),
          axis.text.y = element_text(size=13),
          axis.title = element_text(size=18, face="bold")) +
    #scale_fill_manual(values=c("#008080", "#003366", "#40e0d0")) +
    scale_x_discrete(labels=c("CG", "CHG", "CHH")) +
    ggtitle("Methylation Rate (N=20)") + xlab("") + 
    ylab("Methylation Ratio") + 
    guides(fill=FALSE)
#guides(colour=FALSE, linetype=FALSE)

library("cowplot")

pdf("graphs/SFig_mappingrate_ratio.pdf", width=10, height=5)
plot_grid(p1, p2, ncol=2, labels = c("a", "b"), label_size = 24)
dev.off()

```




## Final plot
```{r}
library("cowplot")

pdf("graphs/SFig_align.pdf", width=10, height=10)

bot_row <- plot_grid(p1, p2, ncol=2, labels = c("b", "c"), label_size = 24)
plot_grid(s, bot_row, nrow=2, labels = c("a", ""), label_size = 24)

dev.off()
```


